In [2]:
import numpy as np 

In [15]:
def discretizeNormalDistribution(mu, sigma, size):
    values = np.zeros(size)
    valuesProbabilities = np.ones(size)*(1/size)
    # sample size 
    N = 100000000
    samples = np.random.normal(mu, sigma, N)
    # partition probabilities 
    probsPartitions = np.linspace(0, 1, size+1)
    for i in range(len(probsPartitions) - 1):
        lowerBound = np.quantile(samples, probsPartitions[i])
        upperBound = np.quantile(samples, probsPartitions[i+1])
        values[i] = samples[(samples > lowerBound) & (samples < upperBound)].mean()
    return values.round(2), valuesProbabilities

In [16]:
mu = 0.12
sigma = 0.15
size = 5
v,vp = discretizeNormalDistribution(mu, sigma, size)

In [17]:
v

array([-0.09,  0.04,  0.12,  0.2 ,  0.33])

In [18]:
vp

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [20]:
v.size

5

In [66]:
np.array([1,2,3]).T

array([1, 2, 3])

In [110]:
k = np.ones(3)
r_k = np.linspace(0.1,0.5,5)
b = np.linspace(1,3,3)


In [111]:
k

array([1., 1., 1.])

In [112]:
r_k

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [113]:
b

array([1., 2., 3.])

In [114]:
np.outer(k,(1+r_k))

array([[1.1, 1.2, 1.3, 1.4, 1.5],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.1, 1.2, 1.3, 1.4, 1.5]])

In [116]:
b.reshape((-1,1)) + np.outer(k,(1+r_k))

array([[2.1, 2.2, 2.3, 2.4, 2.5],
       [3.1, 3.2, 3.3, 3.4, 3.5],
       [4.1, 4.2, 4.3, 4.4, 4.5]])

In [115]:
(b.reshape((-1,1)) + np.outer(k,(1+r_k))).flatten()

array([2.1, 2.2, 2.3, 2.4, 2.5, 3.1, 3.2, 3.3, 3.4, 3.5, 4.1, 4.2, 4.3,
       4.4, 4.5])

In [117]:
np.column_stack((b,b))

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

In [118]:
b.repeat(3)

array([1., 1., 1., 2., 2., 2., 3., 3., 3.])

In [120]:
np.tile(b,3)

array([1., 2., 3., 1., 2., 3., 1., 2., 3.])

In [124]:
Pk = np.array([0.1,0.2,0.3,0.4])
Ps = np.array([0.4,0.6])

np.outer(Pk,Ps).flatten()

array([0.04, 0.06, 0.08, 0.12, 0.12, 0.18, 0.16, 0.24])

In [3]:
import jax.numpy as jnp
a = jnp.array([1,2,3])

a[2]

DeviceArray(3, dtype=int32)

In [127]:
a[2].repeat(10)

DeviceArray([3, 3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int32)

In [11]:
aa = (a[2] == 3)

In [12]:
aa *2

DeviceArray(2, dtype=int32, weak_type=True)

In [9]:
aa

DeviceArray(False, dtype=bool)

In [13]:
aaa = jnp.ones((2,3))

In [19]:
aaa = jnp.array([[1., 2., 3.],
             [1., 2., 3.]])

In [26]:
empiricalEcon = pd.read_csv('constant/empiricalEcon.csv',delimiter=',')
empiricalEcon = empiricalEcon.set_index("year")
empiricalEcon = (empiricalEcon/100).values

In [24]:
import pandas as pd 
empiricalEcon = pd.read_csv('constant/empiricalEcon.csv',delimiter=',')
empiricalEcon = empiricalEcon.set_index("year")
empiricalEcon = (empiricalEcon/100).values
empiricalEcon = empiricalEcon[:,[0,2]]

In [27]:
empiricalEcon

array([[ 0.0724,  0.014 ,  0.1091],
       [ 0.0417,  0.2633,  0.0842],
       [ 0.0346,  0.1462,  0.0645],
       [ 0.0346,  0.0203,  0.0677],
       [ 0.0418,  0.124 ,  0.0765],
       [ 0.0367,  0.2725,  0.0853],
       [ 0.0189, -0.0656,  0.0789],
       [-0.0011,  0.2631,  0.0586],
       [ 0.0352,  0.0446,  0.0389],
       [ 0.0275,  0.0706,  0.0343],
       [ 0.0403, -0.0154,  0.0532],
       [ 0.0268,  0.3411,  0.0594],
       [ 0.0377,  0.2026,  0.0552],
       [ 0.0445,  0.3101,  0.0563],
       [ 0.0448,  0.2667,  0.0505],
       [ 0.0475,  0.1953,  0.0508],
       [ 0.0413, -0.1014,  0.0611],
       [ 0.01  , -0.1304,  0.0349],
       [ 0.0174, -0.2337,  0.02  ],
       [ 0.0286,  0.2638,  0.0124],
       [ 0.038 ,  0.0899,  0.0189],
       [ 0.0351,  0.03  ,  0.0362],
       [ 0.0285,  0.1362,  0.0494],
       [ 0.0188,  0.0353,  0.0453],
       [-0.0014, -0.3849,  0.0183],
       [-0.0254,  0.2345,  0.0047],
       [ 0.0256,  0.1278,  0.0032],
       [ 0.0155,  0.    ,  0

In [33]:
'''
    Economic state calibration 
'''
# Define transition matrix of economical states S
Ps = jnp.array([[0.666943845910281,       0.323002783576127,       0.006773126343361,       0.003280244170230],
                [0.242744495621321,       0.552652993374488,       0.062441903606298,       0.142160607397893],
                [0.142160607397893,       0.062441903606298,       0.552652993374488,       0.242744495621321],
                [0.003280244170230,       0.006773126343361,       0.323002783576127,       0.666943845910281]])
# The possible GDP growth, stock return, bond return
gkfe = jnp.array([[1.15092702581186,0.35018029597671,7.45225509799324,1.96256037691487,2.70289403208730,4.08113333370979,6.38900780341802,6.58200153822790,75.7204565759835],
                    [4.04067574816344,1.52018766753626,11.0127698466567,5.36898678622499,2.74215830217707,4.84525964423984,5.75640718766578,6.41575253485291,76.0184702813153],
                    [1.15092702581186,3.94493112442431,8.01817936174009,1.90525394712031,3.52960682058264,7.20574800383753,6.28203807210335,7.44409304613654,77.1793373563495],
                    [4.04067574816344,5.11493849598385,11.5786941104035,5.31168035643043,3.56887109067241,7.96987431436759,5.64943745635110,7.27784404276155,77.4773510616813]])
# GDP growth depending on current S state
gGDP = gkfe[:,0]/100
# risk free interest rate depending on current S state 
r_b = gkfe[:,1]/100

# GDP growth depending on current S state
gGDP = gkfe[:,0]/100
# risk free interest rate depending on current S state 
r_b = gkfe[:,1]/100
# stock return depending on current S state
r_k = jnp.array([-0.09,  0.04,  0.12,  0.2 ,  0.33])
pk = jnp.array([0.2, 0.2, 0.2, 0.2, 0.2])
# unemployment rate depending on current S state 
Pe = gkfe[:,7:]/100
Pe = Pe[:,::-1]

In [31]:
# empirical econ
empiricalEcon = pd.read_csv('constant/empiricalEcon.csv',delimiter=',')
empiricalEcon = empiricalEcon.set_index("year")
empiricalEcon = (empiricalEcon/100)
# match the empirical states in memoryState
memoryState = np.column_stack((gGDP, r_b))
def similarity(actualState, memoryState = memoryState):
    '''
        state is charactorized as 2 dim vector
    '''
    diffState = np.sum(np.abs(actualState - memoryState), axis = 1)
    distance = np.min(diffState)
    state = np.argmin(diffState)
    return distance, state
_, imaginedEconState = np.vectorize(similarity, signature='(n)->(),()')(empiricalEcon.values[:,[0,2]])
# generate economic states of a certain time window
def generateEcon(yearBegin, yearCount,imaginedEconState,empiricalEcon):
    # single economy generation
    years = empiricalEcon.index.values
    econ = jnp.array(imaginedEconState[np.where(years == yearBegin)[0][0]:np.where(years == yearBegin)[0][0]+yearCount],dtype = int)
    econRate = empiricalEcon[np.where(years == yearBegin)[0][0]:np.where(years == yearBegin)[0][0]+yearCount].values
    return econ, econRate
#**********************************simulation change*****************************************************#
yearBegin = 1999
yearCount = 20
econ, econRate = generateEcon(yearBegin, yearCount,imaginedEconState,empiricalEcon)

In [32]:
imaginedEconState

array([3, 3, 3, 3, 3, 3, 2, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 2, 0, 1, 1, 3,
       3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [34]:
Vgrid = np.load("poorHigh_0.1_4.0" + ".npy")
df_1999 = pd.read_csv("df_1999_30to60.csv")


df = df_1999[(df_1999["skillLevel"] == "Low")&(df_1999["financeExperience"] == "No")]

df["ab"] = 25
df["wealth"] = df["liquidWealth"] + df["investmentAmount"]
codes = {'employed':1, 'unemployed': 0, "retired": 0}
df["employmentStatus"] = df["employmentStatus"].map(codes)
codes = {'owner':1, 'renter': 0}
df["ownership"] = df["ownership"].map(codes)
initialStates = df[["ageHead","wealth","ab","year","employmentStatus","ownership","participation"]]
initialStates["year"] = imaginedEconState[0]
initialStates = jnp.array(initialStates.values)

<ipython-input-34-a1a78db660c7>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ab"] = 25
<ipython-input-34-a1a78db660c7>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["wealth"] = df["liquidWealth"] + df["investmentAmount"]
<ipython-input-34-a1a78db660c7>:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guid